#
# exceptions.py
#

class AllOtherErrors(Exception):
    pass

